### ISSUE TITLE
Comparisons With YOLOv5

### ISSUE THREAD

**Issue by augmentedstartups** [ibaiGorordo/ONNX-YOLOv6-Object-Detection#1]
Hi there, I have seen a few videos with YOLOv6 on YouTube, specifically with YOLOv5. I noticed that v6 loses detections and v5 appears more stable. Why is this?

**Comment by ibaiGorordo** [comment]
Hi,

with the limited test that I have done (only visual, no proper comparison), I think it might be because YOLOv6 is struggling more with close objects and is also trying hard to detect smaller objects.

Also, the original authors mention that the model is focused for industrial applications, so they might have done something with the model for that purpose, which might explain why it works better for smaller objects than closer large objects.
